"""Make exam attempt question choice optional

Revision ID: 5c85dd6b37ee
Revises: dc26d271b2f4
Create Date: 2024-05-29 21:03:34.086608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c85dd6b37ee'
down_revision = 'dc26d271b2f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_choice', schema=None) as batch_op:
        batch_op.alter_column('choice_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_choice', schema=None) as batch_op:
        batch_op.alter_column('choice_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
